FORMAT: 1A

# Casumo Test API
Implementation of Caravelo test Use Case for UI implementation

## Media Types
Requests with a message-body are using plain JSON to set or update resource states.

## Error States
The common [HTTP Response Status Codes](https://github.com/for-GET/know-your-http-well/blob/master/status-codes.md) are used.

## Data Structures
:[](datastructures/author.mson)
:[](datastructures/book.mson)


:[](resources/book.apib)
:[](resources/author.apib)