# Group Author

Provides an interface to list authors on the sistem

## authors [/authors]

## Get Authors [GET]

+ Response 200  (application/json)
    + Attributes (array[Author,Author-2,Author-3,Author-4,Author-5,Author-6,Author-7])